### PR TITLE
Log4net wrapper extension.

### PR DESCRIPTION
**Pull request by ma499**

### CODE REVIEW

**Comment by ma499** [comment]
Hey, what's happening with this?

We want to use this in our production system. Ideally we'd like to avoid spinnning up our build process, and/or maintaining our own fork, to get a nuget package for the log4net extension. Anything we can do to help speed up the pull request?

**Comment by RyannosaurusRex** [comment]
+1.  At my company we're using Serilog for Nimbus and Log4Net for everything else (a whole lot of stuff), so it'd be awesome if you could outline anything left needed to wrap this up and get it in.

**Comment by DamianMac** [comment]
Looks fine, you have to remember that :
a. this is open source and nobody is being paid for it
b. I'm probably in a different timezone to you.

Patience :)

**Comment by DamianMac** [comment]
and it doesn't build.
I'll have a look at it tonight

**Comment by ma499** [comment]
Cool! Thanks. Sorry my colleague was tearing their hair out trying to build the whole thing on our CI system... We were concerned that there didn't seem to have been any pull requests accepted since mid-Jan. We'll likely have a few more on the way :-)

**Comment by ma499** [comment]
Eeek! Is your build server public? Happy to take a look at it.

**Comment by DamianMac** [comment]
Nope, it's my build server I use for a few projects. I'll get it sorted for you soon.

**Comment by DamianMac** [comment]
You hadn't committed any of the log4net binaries (.dll in your gitignore ?)

Built now https://www.nuget.org/packages/Nimbus.Logger.Log4net/

**Comment by ma499** [comment]
Ah, whoops, I'll have to check that in the morning. Thanks!

**Pull request merged**
