### PR TITLE
Enable Heartbeat Overload

### PR DESCRIPTION
**Pull request by KodrAus**
I'm not sure if this little feature is something you'll all disagree with on principal. We've found the Heartbeat is great for keeping tabs on how handlers are running, but have been held back by not being able to touch any of it (adding a different identifier than the machine / process name for example).

I've added a simple setting for modifying / overwriting the Heartbeat event before it's published.

For example, replacing the default `HeartbeatEvent` with a different class in BusBuilderConfiguration:

```
    .Configure()
    .WithHeartbeat(beat => new MyCustomHeartbeat
    {
        MyCustomProperty = someValue,
        MachineName = beat.MachineName,
        ...
     })
    .Build()
```

Or if you find `PerformanceCounters` offensive:

```
.WithHeartbeat(beat => 
{
    beat.PerformanceCounters = new PerformanceCounterDto[0];
    return beat;
})
```

If you're happy with the idea / implementation then where should I put unit tests?

### CODE REVIEW

**Comment by KodrAus** [comment]
Didn't intend to include all the other stuf. Should've paid attention. The only relevant commits are 3c4f28d and 3c4f28d

**Comment by DamianMac** [comment]
I really like the idea actually, I might look at cherry picking it for a 2.x build

**Comment by uglybugger** [comment]
We should be able to achieve something like this but a whole lot more flexible using an outbound interceptor once we've gotten rid of `BrokeredMessage`. Watch this space :)

**Comment by KodrAus** [comment]
Sounds good, it'd be cool if you could use the interceptors to change the dispatcher too

**Pull request closed without merging**
