### PR TITLE
Path Generation

### PR DESCRIPTION
**Pull request by BenGale**
We need the ability to have a finer control over the names generated within azure. For this I've made the component responsible injectable via an extension method. 
It defaults to the way things worked before so no changes would need to be made.

### CODE REVIEW

**Comment by uglybugger** [comment]
This looks great. Thank you :)

I'll have a more detailed look over the next day or so and get it merged.


-- 
<http://www.customsig.com/Signature/Link/andrewh%40uglybugger.org>

**Comment by BenGale** [comment]
Hey, where are we at with the different open requests?

**Comment by DamianMac** [comment]
This one can probably be best achieved by building a custom IRouter and specifying WithRouter() in your configuration code.

I know you'd probably be duplicating a bit of code for your path generator, but otherwise we have two extensions points for essentially the same thing.

**Comment by BenGale** [comment]
Ok, I'll take a look at that and see if it fits better.

**Comment by BenGale** [comment]
Good shout, I went down the complete wrong path there.

**Pull request closed without merging**
